Allow custom branch to be passed in
dependabot/dependabot-script pull request #495
Opened 2020-11-16 20:36 UTC by mlarraz

2021-01-02 10:42 UTC, stijnb1234 requested changes
Works fine. But please use the branch variable you create at line 28 in the code.

2021-01-03 19:49 UTC, stijnb1234 approved these changes
Works fine!

2021-01-12 02:51 UTC, mlarraz commented
Is anything else needed for this to get merged in?

2021-04-15 14:35 UTC, feelepxyz approved these changes
👍

2021-04-15 14:35 UTC, merged